name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build knowledge-base-service image
        run: docker build -t 2252635/knowledge-base-service:latest ./knowledge-base-service

      - name: Push knowledge-base-service image
        run: docker push 2252635/knowledge-base-service:latest

      - name: Build user-service image
        run: docker build -t 2252635/user-service:latest ./user-service

      - name: Push user-service image
        run: docker push 2252635/user-service:latest
